<?php

declare(strict_types=1);

namespace ConstructionStages\Http;

interface ActionContract
{
    /**
     * Execute the action with the given HTTP request and return an HTTP response.
     *
     * @param Request $request The HTTP request to execute the action with.
     *
     * @return Response The HTTP response generated by executing the action.
     */
    public function execute(Request $request): Response;
}
